---

- name: Deploy OpenBlog Playbook
  hosts: all
  gather_facts: True
  become: true

  vars_files:
    - ./secrets/encrypted-variables.yml

  vars:
    app_name: 'openblog'
    app_git_repo_name: '{{ app_name }}'
    repo_auth_username: ''
    repo_auth_password: ''

  roles:
    - deploy-java-app
